sudo: required
language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: LANGUAGE=cpp
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: LANGUAGE=python2
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: LANGUAGE=python3
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: LANGUAGE=dotnet
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: LANGUAGE=java

    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: LANGUAGE=cpp
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: LANGUAGE=python2
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: LANGUAGE=python3
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: LANGUAGE=dotnet
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: LANGUAGE=java

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
