name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env
    - name: Build C++ project
      run: make --directory=ci devel_cpp
    - name: Test C++ project
      run: make --directory=ci test_cpp
